update: github actions

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -26,13 +26,22 @@ jobs:
 
       - name: Install ChromeDriver
         run: |
-          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')  # Extracts only the major.minor.build
-          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
+          sudo apt-get update
+          sudo apt-get install -y chromium-browser
+          CHROME_VERSION=$(chromium-browser --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')  
+          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "ERROR")
+  
+          if [[ "$CHROMEDRIVER_VERSION" == "ERROR" ]]; then
+            echo "Could not find matching ChromeDriver version. Using latest stable version."
+            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
+          fi
+  
           echo "Installing ChromeDriver version $CHROMEDRIVER_VERSION"
           wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
           unzip chromedriver_linux64.zip
           sudo mv chromedriver /usr/local/bin/
           sudo chmod +x /usr/local/bin/chromedriver
+  
   
 
       - name: Install dependencies
